// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModMail.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModMail.Migrations
{
    [DbContext(typeof(GuildContext))]
    [Migration("20211106122536_Threadsv1")]
    partial class Threadsv1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.1.21452.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModMail.Data.ModMailGuildEntity", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Commands")
                        .HasColumnType("text");

                    b.Property<string>("Groups")
                        .HasColumnType("text");

                    b.Property<decimal>("ModMailCategory")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ModMailLogChannel")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("ModMail.Data.ModMailThreadEntity", b =>
                {
                    b.Property<decimal>("Recepient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Channel")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Recepient");

                    b.HasIndex("GuildId");

                    b.ToTable("ModMailThreadEntity");
                });

            modelBuilder.Entity("ModMail.Data.ModMailThreadEntity", b =>
                {
                    b.HasOne("ModMail.Data.ModMailGuildEntity", "GuildEntity")
                        .WithMany("ModMailThreads")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildEntity");
                });

            modelBuilder.Entity("ModMail.Data.ModMailGuildEntity", b =>
                {
                    b.Navigation("ModMailThreads");
                });
#pragma warning restore 612, 618
        }
    }
}
